repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          ['@commitlint/cli', '@commitlint/config-conventional']
